name: Build and deploy Node.js app to Azure Web App - app-step4-58

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm install
          npm run build

      - name: Prepare release zip with minimum structure
        run: |
          mkdir -p release/_next
          cp -r .next/standalone/* release/
          cp -r .next/static release/_next/
          cp package.json release/
          cp package-lock.json release/
          [ -f server.js ] && cp server.js release/
          [ -f .next/trace ] && cp .next/trace release/        # ← 追加
          cd release
          zip -r ../release.zip .

      - name: Show contents of release.zip
        run: unzip -l release.zip

      - name: Upload artifact for deploy step
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-step4-58'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6641BB71A5E455B91FE964937BDF752 }}
