name: Build and deploy Node.js app to Azure Web App - app-step4-58

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install and build
        env:
          NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.NEXT_PUBLIC_API_ENDPOINT }}
        run: |
          npm install
          npm run build

      - name: Check if next.config.ts exists
        id: check_next_config
        run: |
          if [ -f next.config.ts ]; then
            echo "next_config_exists=true" >> $GITHUB_OUTPUT
          else
            echo "next_config_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Zip build artifacts for deployment
        run: |
          if [ "${{ steps.check_next_config.outputs.next_config_exists }}" = "true" ]; then
            echo "Including next.config.ts in zip"
            zip -r release.zip .next/standalone .next/static public package.json next.config.ts
          else
            echo "Excluding next.config.ts from zip"
            zip -r release.zip .next/standalone .next/static public package.json
          fi

      - name: Check contents of release.zip
        run: unzip -l release.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-step4-58'  # Azure App Service 名に合わせて変更
          slot-name: 'Production'
          package: '.'  # ← ZIPを展開したカレントディレクトリ
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B6641BB71A5E455B91FE964937BDF752 }}
